apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.secret.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.secret.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD }}
  SECRET_KEY: {{ .Values.secret.SECRET_KEY }}
  DB_HOST: {{ .Values.secret.DB_HOST }}
  DB_PORT: {{ .Values.secret.DB_PORT | quote }}