apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev
type: Opaque
stringData:
  POSTGRES_DB: db
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: changeme123
  SECRET_KEY: v!kyc=--$*^h67u-^rhau64x(_5=63a0127a!(tt7@^loo3rf+
  DB_HOST: postgres-svc
  DB_PORT: "5432"