apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-stable
  namespace: dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: django
      track: stable
  template:
    metadata:
      labels:
        app: django
        track: stable
    spec:
      containers:
        - name: django-container
          image: us-central1-docker.pkg.dev/research-502304/canary-repo/canary-app:1
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "125m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          startupProbe:
            httpGet:
              path: /start/
              port: 8000
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /ready/
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /live/
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: SECRET_KEY
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PORT